language: node_js
node_js:
  - "6.10"

matrix:
  fast_finish: true
cache: yarn

install:
  - yarn
  - yarn run bootstrap

script: yarn test:ci
deploy:
  provider: script
  script: yarn deploy:ci
  on:
    all_branches: true
