language: node_js
node_js:
  - "8"

matrix:
  fast_finish: true
cache: yarn

before_install:
  - yarn global add lerna

install:
  - lerna bootstrap

script: lerna run test
deploy:
  - provider: script
    script: lerna publish --canary --yes
    on:
      branch: master