service:
  name: graphql

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

package:
  individually: true

functions:
  graphql:
    handler: handler.graphql
    events:
      - http:
          method: get
          path: graphql
      - http:
          method: post
          path: graphql
  graphiql:
    handler: handler.graphiql
    events:
      - http:
          method: get
          path: graphiql
