service:
  name: terrorizer-graphql

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.4

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
